version: "3.7"
services:
  nifi-no-volumes:
    build:
      context: nifi-no-volumes/.
      dockerfile: Dockerfile
    #image: nfti/nifi:0.1
    image: samdavis2/nifi-no-volumes:1.8.0
    container_name: nifi
    ports:
    - "8080:8080" # User Interface
    - "9500:9500" #Requests
    - "8556:8556" # ZeroMq
    - "8000:8000" # Java Debug Port

  docker-compose-java:
    build:
      context: docker-compose-java-alpine/.
      dockerfile: Dockerfile
    image: samdavis2/docker-compose-java:2.1
    container_name: docker-compose-java

  npm-builder:
    build:
      context: node_builder/.
      dockerfile: Dockerfile
    image: samdavis2/npm-builder:1.0
    container_name: npm-builder




