version: "3.7"
services:
  nifi-no-volumes:
    build:
      context: nifi-no-volumes/.
      dockerfile: Dockerfile
    #image: nfti/nifi:0.1
    image: samdavis2/nifi-no-volumes:1.8.0
    container_name: nifi
    ports:
    - "8080:8080" # User Interface
    - "9500:9500" #Requests
    - "8556:8556" # ZeroMq
    - "8000:8000" # Java Debug Port

  docker-compose-java:
    build:
      context: docker-compose-java/.
      dockerfile: Dockerfile
    image: samdavis2/docker-compose-java:j8-1.24.0-rc1
    container_name: docker-compose-java




